apiVersion: v1
kind: Service
metadata:
  name: ilb-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: openlegacy-api
spec:
  type: LoadBalancer
  selector:
    app: openlegacy-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP