apiVersion: apps/v1
kind: Deployment  # Specify the type of object to create
metadata:
  name: openlegacy   # Name for object
  namespace: app
spec:
  selector:
    matchLabels:
      app: openlegacy
  replicas: 3     # Run 3 replicas of this Pod
  template:
    metadata:
      labels:
        app: openlegacy
    spec:
      containers:
      - name: openlegacy # Name of the container to run
        image: igalonso/openlegacy:1.0 # Container image
        env:
        - name: "PORT"
          value: "8080"      

---
apiVersion: v1
kind: Service
metadata:
  name: openlegacy-service
  namespace: app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: openlegacy
  sessionAffinity: None
  type: ClusterIP
